apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: push-notifications
  namespace: push-notifications
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - push.goatlab.dev
      secretName: letsencrypt-clouddns
  rules:
    - host: push.goatlab.dev
      http:
        paths:
          - path: /
            backend:
              serviceName: push-notifications-svc
              servicePort: 80
