apiVersion: apps/v1
kind: Deployment
metadata:
  name: twilio-1ck-svc
  namespace: 1ck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twilio-1ck-svc
  template:
    metadata:
      labels:
        app: twilio-1ck-svc
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: 1ck-twilio
        image: registry.gitlab.com/goatlab/corporate/moutain/mountain/1ck-twilio:0.3
        imagePullPolicy: Always
        ports:
        - name: twilio-1ck-port
          containerPort: 3000
        env:
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: 1ck-twilio-secret
              key: TWILIO_ACCOUNT_SID
        - name: TWILIO_SERVICE_SID
          valueFrom:
            secretKeyRef:
              name: 1ck-twilio-secret
              key: TWILIO_SERVICE_SID
        - name: TWILIO_API_KEY
          valueFrom:
            secretKeyRef:
              name: 1ck-twilio-secret
              key: TWILIO_API_KEY
        - name: TWILIO_API_SECRET
          valueFrom:
            secretKeyRef:
              name: 1ck-twilio-secret
              key: TWILIO_API_SECRET
        - name: KEYCLOAK_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: 1ck-twilio-secret
              key: KEYCLOAK_TOKEN_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: twilio-1ck-svc
  namespace: 1ck
  labels:
    app: twilio-1ck-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: twilio-http
  selector:
    app: twilio-1ck-svc
