apiVersion: v1
kind: Secret
metadata:
  name: 1ck-twilio-secret
  namespace: 1ck
type: Opaque
data:
  TWILIO_ACCOUNT_SID: ACec5d1ef31ec9acead7f17e90c6c4ba85
  TWILIO_API_KEY: SK4da3700bf6ffe4d7062e8fdb1316ed74
  TWILIO_API_SECRET: pwsHGjDHNVLFMeTU9J3rQpszh0PFj0Av
  KEYCLOAK_TOKEN_SECRET: 1IQSeEVitLWNxauA7nvuLhhvBEQc4iGTHpYdlAA4z1Xb_0BzdqeFsFurZ7GQAAG_P4q-NjrsDXoEd43WOgnudg
