apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 1ck-twilio
  namespace: 1ck
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - twilio.oneclinick.com
      secretName: letsencrypt-clouddns
  rules:
    - host: twilio.oneclinick.com
      http:
        paths:
          - path: /token
            backend:
              serviceName: twilio-1ck-svc
              servicePort: 80
