apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-example
  namespace: keycloak
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - keycloak.35.193.196.208.nip.io
    secretName: letsencrypt-prod
  rules:
  - host: keycloak.35.193.196.208.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak-http
          servicePort: 8080
      - path: /auth
        backend:
          serviceName: keycloak-http
          servicePort: 8080