apiVersion: v1
kind: Service
metadata:
  name: keycloak-http
  namespace: keycloak
  labels:
    app: keycloak-http
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: keycloak-http
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-http
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-http
  template:
    metadata:
      labels:
        app: keycloak-http
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi
        env:
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: keycloak_user
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: keycloak_password
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_LOGLEVEL
          value: "DEBUG"
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: pg_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: pg_password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: pg_db
        - name: DB_ADDR
          value: pg-keycloak
        - name: DB_PORT
          value: "5432"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080