apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque
data:
  keycloak_user: YWRtaW4=
  keycloak_password: YWRtaW4=
  pg_user: a2V5Y2xvYWs=
  pg_password: a2V5Y2xvYWtwYXNzd29yZA==
  pg_db: a2V5Y2xvYWtfZGI=
