apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque
data:
  keycloak_user: admin
  keycloak_password: admin
  pg_user: keycloak
  pg_password: keycloakpassword
  pg_db: keycloak_db
