apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 1ck-pusher
  namespace: 1ck
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - pusher-dev.goatlab.dev
    secretName: letsencrypt-clouddns
  rules:
  - host: pusher-dev.goatlab.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: pusher-1ck-svc
          servicePort: 80
