apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dummy
  namespace:  dummy
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
    - host: dummy.35.222.213.192.nip.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: http-svc
              servicePort: http