apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dummy
  namespace: dummy
  annotations:
    kubernetes.io/ingress.class: kong
    plugins.konghq.com: oidc-keycloak, add-request-transformer
spec:
  tls:
  - hosts:
    - gateway.goatlab.dev
    secretName: letsencrypt-clouddns
  rules:
    - host: gateway.goatlab.dev
      http:
        paths:
          - path: /dummy
            backend:
              serviceName: http-svc
              servicePort: 80
