apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-keycloak
  namespace: dummy
config:
  client_id: kong
  client_secret: 3da87d1d-aad3-45ed-b963-49668705c7dd
  discovery: https://keycloak.35.193.196.208.nip.io/auth/realms/apps/.well-known/openid-configuration
plugin: oidc
