apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-keycloak
  namespace: dummy
config:
  client_id: kong
  client_secret: 4a871543-8546-45df-9b8d-00bd09939253
  discovery: https://keycloak.goatlab.dev/auth/realms/apps/.well-known/openid-configuration
  access_token_header_name: Authorization
  access_token_header_as_bearer: "yes"
  disable_userinfo_header: "no"
  disable_id_token_header: "no"
plugin: oidc
