apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-keycloak
  namespace: dummy
config:
  client_id: kong
  client_secret: 448966fd-5c2c-4229-b1a4-87b2e6e8c236
  discovery: https://keycloak.oneclinick.com/auth/realms/apps/.well-known/openid-configuration
  access_token_header_name: x-jwt-token
  access_token_header_as_bearer: "yes"
  disable_userinfo_header: "no"
  disable_id_token_header: "no"
plugin: oidc
