apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: upload
  namespace: upload
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - upload.oneclinick.com
      secretName: letsencrypt-clouddns
  rules:
    - host: upload.oneclinick.com
      http:
        paths:
          - path: /
            backend:
              serviceName: upload-svc
              servicePort: 80
