apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-svc
  namespace: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-svc
  template:
    metadata:
      labels:
        app: upload-svc
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: upload-server
          image: registry.gitlab.com/goatlab/corporate/moutain/mountain/goat-upload:0.1
          imagePullPolicy: Always
          ports:
            - name: upload-port
              containerPort: 4100
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: upload-secret
                  key: PORT
            - name: UPLOAD_DIR
              valueFrom:
                secretKeyRef:
                  name: upload-secret
                  key: UPLOAD_DIR
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: upload-secret
                  key: DEBUG
            - name: PROVIDERS
              valueFrom:
                secretKeyRef:
                  name: upload-secret
                  key: PROVIDERS
            - name: GOOGLE_CLOUD_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: upload-secret
                  key: GOOGLE_CLOUD_PROJECT_ID
            - name: GOOGLE_CLOUD_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: upload-secret
                  key: GOOGLE_CLOUD_BUCKET_NAME
            - name: MAX_UPLOAD_SIZE
              valueFrom:
                secretKeyRef:
                  name: upload-secret
                  key: MAX_UPLOAD_SIZE
---
apiVersion: v1
kind: Service
metadata:
  name: upload-svc
  namespace: upload
  labels:
    app: upload-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4100
      protocol: TCP
      name: upload-http
  selector:
    app: upload-svc
