apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 1ck-twilio-client
  namespace: 1ck
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - twilio.35.193.196.208.nip.io
    secretName: tls-letsencrypt-client
  rules:
  - host: twilio.35.193.196.208.nip.io
    http:
      paths:
      - path: /quickstart
        backend:
          serviceName: twilio-client-svc
          servicePort: 80
