apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server-formio
  namespace: formio
  annotations:
    kubernetes.io/ingress.class: kong
    # configuration.konghq.com: formio-configuration
    plugins.konghq.com: add-request-transformer, jwt-plugin
spec:
  tls:
    - hosts:
        - gateway.goatlab.dev
      secretName: letsencrypt-clouddns
  rules:
    - host: gateway.goatlab.dev
      http:
        paths:
          - path: /server/api/formio
            backend:
              serviceName: formio-http
              servicePort: 3001
