apiVersion: v1
kind: Secret
metadata:
  name: formio-secret
  namespace: formio
type: Opaque
data:
  MONGO_PORT: 27017
  MONGO_ROOT_USERNAME: admin
  MONGO_ROOT_PASSWORD: admin
  MONGO_DB_USER: user
  MONGO_DB_PASSWORD: user
  MONGO_DB_NAME: goat
  MONGO_DB_HOST: mongo-0.mongo-gvr
  FORMIO_PROTOCOL: https
  FORMIO_HOST: gateway.oneclinick.com
  FORMIO_PORT: 443
  FORMIO_BASE_PATH: /api/formio
  FORMIO_VERSION: v1.46.0
  FORMIO_TEMPLATES_FOLDER: ./Formio/templates
  PROJECT_TEMPLATE: xinerlink
  ROOT_EMAIL: admin@example.com
  ROOT_PASS: admin@example.com
  MONGO_SECRET: FTFaVuIdSv4Hj2bjnwae
  MONGO_HIGH_AVAILABILITY: 0
  JWT_SECRET: CHANGEME
  JWT_SECRET_BUFFER: 1IQSeEVitLWNxauA7nvuLhhvBEQc4iGTHpYdlAA4z1Xb_0BzdqeFsFurZ7GQAAG_P4q-NjrsDXoEd43WOgnudg
  JWT_EXPIRE_TIME: 240
  LB_SKIP_JWT: false
  SMTP_HOST:
  SMTP_SSL:
  SMTP_PORT:
  SMTP_USER:
  SMTP_PASS:
  LABORUM_SCRATHER_VERSION: 0.12
  SCRATCH_CONTAINERS: 1
  KEYCLOAK_ENABLED: true
  KEYCLOAK_URL: https://keycloak.oneclinick.com
  KEYCLOAK_CLIENT_ID: kong
  KEYCLOAK_SECRET: 448966fd-5c2c-4229-b1a4-87b2e6e8c236
  KEYCLOAK_REALM: apps
