apiVersion: v1
kind: Secret
metadata:
  name: formio-secret
  namespace: formio
type: Opaque
data:
  MONGO_PORT: MjcwMTc=
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: YWRtaW4=
  MONGO_DB_USER: dXNlcg==
  MONGO_DB_PASSWORD: dXNlcg==
  MONGO_DB_NAME: Z29hdA==
  MONGO_DB_HOST: bW9uZ28tMC5tb25nby1ndnI=
  FORMIO_PROTOCOL: aHR0cA==
  FORMIO_HOST: Zm9ybWlvLWh0dHA=
  FORMIO_PORT: MzAwMQ==
  FORMIO_TEMPLATES_FOLDER: Li9Gb3JtaW8vdGVtcGxhdGVz
  PROJECT_TEMPLATE: eGluZXJsaW5r
  ROOT_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=
  ROOT_PASS: YWRtaW5AZXhhbXBsZS5jb20=
  MONGO_SECRET: RlRGYVZ1SWRTdjRIajJiam53YWU=
  MONGO_HIGH_AVAILABILITY: MA==
  JWT_SECRET: Q0hBTkdFTUU=
  JWT_EXPIRE_TIME: MjQw
  LB_SKIP_JWT: VHJ1ZQ==
  SMTP_HOST: Tm9uZQ==
  SMTP_SSL: Tm9uZQ==
  SMTP_PORT: Tm9uZQ==
  SMTP_USER: Tm9uZQ==
  SMTP_PASS: Tm9uZQ==
  LABORUM_SCRATHER_VERSION: MC4xMg==
  SCRATCH_CONTAINERS: MQ==
