apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: formio-configuration
  namespace: formio
route:
  preserve_host: true
  strip_path: true
  protocols:
  - http
  - https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: formio
  namespace: formio
  annotations:
    kubernetes.io/ingress.class: kong
    configuration.konghq.com: formio-configuration
    plugins.konghq.com: add-request-transformer, oidc-keycloak
spec:
  tls:
    - hosts:
        - gateway.goatlab.dev
      secretName: letsencrypt-clouddns
  rules:
    - host: gateway.goatlab.dev
      http:
        paths:
          - path: /api/formio
            backend:
              serviceName: formio-http
              servicePort: 3001
