apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-keycloak
  namespace: formio
config:
  client_id: loopback
  client_secret: 01accea2-5dba-4f9d-8f75-b8a5ce119196
  discovery: https://keycloak.35.193.196.208.nip.io/auth/realms/apps/.well-known/openid-configuration
plugin: oidc
