apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: formio-role
  namespace: formio
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - nodes
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: formio-role-binding
  namespace: formio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: formio-role
subjects:
- kind: ServiceAccount
  name: formio-serviceaccount
  namespace: formio