apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kong-admin
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - admin.oneclinick.com
      secretName: letsencrypt-clouddns
  rules:
    - host: admin.oneclinick.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kong-ingress-controller
              servicePort: 8001
