apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kong-admin
  namespace: kong
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - admin.35.193.196.208.nip.io
    secretName: tls-kong-admin
  rules:
  - host: admin.35.193.196.208.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: kong-ingress-controller
          servicePort: 8001
