apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: entrypoint
  namespace: kong
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - gateway.oneclinick.com
        # - 35.184.13.185.nip.io
      secretName: letsencrypt-clouddns
  rules:
    - host: gateway.oneclinick.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kong-proxy
              servicePort: 443
