apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: loopback-configuration
  namespace: formio
proxy:
  path: /api
route:
  preserve_host: true
  strip_path: true
  protocols:
    - http
    - https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loopback
  namespace: formio
  annotations:
    kubernetes.io/ingress.class: kong
    plugins.konghq.com: add-request-transformer, oidc-loopback-keycloak
    configuration.konghq.com: loopback-configuration
spec:
  tls:
    - hosts:
        - gateway.oneclinick.com
      secretName: letsencrypt-clouddns
  rules:
    - host: gateway.oneclinick.com
      http:
        paths:
          - path: /api/loopback-dev
            backend:
              serviceName: loopback-dev-http
              servicePort: 3000
    - host: gateway.oneclinick.com
      http:
        paths:
          - path: /api/loopback
            backend:
              serviceName: loopback-prod-http
              servicePort: 3000
