apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loopback
  namespace: formio
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: kong
    # configuration.konghq.com: formio-configuration
spec:
  tls:
  - hosts:
    - 35.222.213.192.nip.io
    secretName: tls-example-loopback
  rules:
  - host: 35.222.213.192.nip.io
    http:
      paths:
      - path: /api/loopback
        backend:
          serviceName: loopback-http
          servicePort: 3000
