apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: loopback-configuration
  namespace: formio
proxy:
  name: loopback
  protocol: http
  host: formio.formio-http.formio-port
  path: /api
route:
  paths:
  - /loopback
  methods:
  - POST
  - GET
  - PUT
  - DELETE
  strip_path: true
  preserve_host: false
  protocols:
  - http
  - https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loopback
  namespace: formio
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    configuration.konghq.com: loopback-configuration
spec:
  tls:
  - hosts:
    - 35.222.213.192.nip.io
    secretName: tls-example-loopback
  rules:
  - host: 35.222.213.192.nip.io
    http:
      paths:
      - path: /loopback
        backend:
          serviceName: loopback-http
          servicePort: loopback-port