apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: loopback-configuration
  namespace: formio
proxy:
  protocol: http
  path: /api
  connect_timeout: 10000
  retries: 10
  read_timeout: 10000
  write_timeout: 10000