apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-loopback-keycloak
  namespace: formio
config:
  client_id: loopback
  client_secret: 95afa20e-e96f-430c-b1e6-b1a7ab2c738b
  bearer_only: "yes"
  discovery: https://keycloak.oneclinick.com/auth/realms/apps/.well-known/openid-configuration
  access_token_header_name: Authorization
  access_token_header_as_bearer: "yes"
  introspection_endpoint: https://keycloak.oneclinick.com/auth/realms/apps/protocol/openid-connect/token/introspect
  disable_userinfo_header: "yes"
  disable_id_token_header: "yes"
plugin: oidc
