apiVersion: v1
kind: Secret
metadata:
  name: pusher-secret
  namespace: formio
type: Opaque
data:
  PUSHER_APP_ID: 791972
  PUSHER_APP_KEY: e308a51cf17ec0881980
  PUSHER_APP_SECRET: e64e6e6263f093cb4b79
  PUSHER_APP_CLUSTER: us2
