apiVersion: v1
kind: Secret
metadata:
  name: pusher-prod-secret
  namespace: formio
type: Opaque
data:
  PUSHER_APP_ID: OTg5OTMy
  PUSHER_APP_KEY: M2ZiNjBkYjgyMmYzMDczM2UwYTQ=
  PUSHER_APP_SECRET: NGUyNzI0OTQyODIyMmNiMTAxZGQ=
  PUSHER_APP_CLUSTER: dXMy
  SHOULD_BROADCAST: VHJ1ZQ==
